[project]
authors = ["helehex <helehex@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Falling sand simulation."
name = "dustbin"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
game = "magic run mojo src/game.mojo"

[dependencies]
max = "==24.6.0.dev2024090705"
sdl2 = ">=2.30.7,<3"
